top_srcdir=../../..
top_builddir=$(top_srcdir)

CPPFLAGS:=-DSTATICLIB $(CPPFLAGS)

include $(top_srcdir)/makerules/common.mk

SRC= \
	miniwget.cpp \
	minixml.cpp \
	igd_desc_parse.cpp \
	minisoap.cpp \
	miniupnpc.cpp \
	upnpreplyparse.cpp \
	upnpcommands.cpp \
	minissdpc.cpp \
	upnperrors.cpp

LIB=miniupnpc

include $(top_srcdir)/makerules/lib.mk