MAKERULES=../../makerules
include $(MAKERULES)/configure.mk

SRC=general/databuffer.cpp \
	audio.cpp \
	audio_id.c \
	cdaudio.cpp \
	constants.cpp \
	decoding.cpp \
	openal/buffer.cpp \
	openal/exception.cpp \
	openal/source.cpp \
	openal_track.c \
	openal_error.cpp \
	playlist.c \
	stream.cpp \
	track.c

LIB=sound

include $(MAKERULES)/lib.mk
