MAKERULES=../../makerules
include $(MAKERULES)/configure.mk

SRC=general/databuffer.cpp \
	general/raii_counter.cpp \
	interface/devicelist.cpp \
	interface/stringarray.hpp \
	audio.cpp \
	audio_id.c \
	cdaudio.cpp \
	oggvorbis.c \
	openal/buffer.cpp \
	openal/devicelist.cpp \
	openal/exception.cpp \
	openal/source.cpp \
	openal_track.c \
	openal_error.cpp \
	playlist.c \
	track.c

LIB=sound

include $(MAKERULES)/lib.mk
